### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by doronbehar** [f1u77y/wmc-mpris#2]
Hello,

I've encountered this project via the [AUR package](https://aur.archlinux.org/packages/web-media-controller-mpris-git/) when looking for a way to control media players in the browser via mpris. I've managed to compile it successfully but I don't know what to do next.

Should I put the file `me.f1u77y.web_media_controller.firefox.json` somewhere inside my `~/.mozilla/*.default` directory?

Does this work only with certain websites?

**Comment by f1u77y** [comment]
Thanks for reminding me, I'll add a README.

**Comment by f1u77y** [comment]
I've added a README. If something's still not understandable, feel free to give feedback in this issue.
